import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import {
  Activity,
  TrendingUp,
  Clock,
  CheckCircle2,
  Mail,
  FileText,
  Users,
  Calendar,
  Sparkles,
  Zap,
  Brain,
  Timer,
  ArrowUp,
  ArrowDown,
  MessageSquare,
  Target,
  Radio,
} from 'lucide-react';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
} from 'recharts';
import LiveActivityFeed from '@/components/collaboration/LiveActivityFeed';
import { useRealtimeActivity } from '@/hooks/useRealtimeActivity';

interface ActivityItem {
  id: string;
  type: 'task' | 'email' | 'meeting' | 'document' | 'ai';
  action: string;
  description: string;
  time: string;
  aiAssisted?: boolean;
  timeSaved?: number;
}

interface ProductivityStat {
  label: string;
  value: number;
  unit: string;
  change: number;
  icon: React.ElementType;
}

const todayActivities: ActivityItem[] = [
  { id: '1', type: 'ai', action: 'AI Generated', description: 'Meeting minutes for Q4 Planning session', time: '10 mins ago', aiAssisted: true, timeSaved: 25 },
  { id: '2', type: 'task', action: 'Completed', description: 'Review marketing proposal', time: '32 mins ago', aiAssisted: false },
  { id: '3', type: 'email', action: 'AI Analyzed', description: 'Sentiment analysis on 12 emails', time: '1 hour ago', aiAssisted: true, timeSaved: 15 },
  { id: '4', type: 'meeting', action: 'Scheduled', description: 'Stakeholder sync with Product team', time: '2 hours ago', aiAssisted: false },
  { id: '5', type: 'ai', action: 'AI Extracted', description: '5 tasks from meeting transcript', time: '2 hours ago', aiAssisted: true, timeSaved: 20 },
  { id: '6', type: 'document', action: 'Created', description: 'Project status report template', time: '3 hours ago', aiAssisted: true, timeSaved: 30 },
  { id: '7', type: 'task', action: 'Updated', description: 'Changed priority of API integration', time: '4 hours ago', aiAssisted: false },
  { id: '8', type: 'email', action: 'AI Drafted', description: 'Response to vendor inquiry', time: '5 hours ago', aiAssisted: true, timeSaved: 10 },
];

const weeklyData = [
  { day: 'Mon', tasks: 12, emails: 24, meetings: 3, aiActions: 8 },
  { day: 'Tue', tasks: 15, emails: 18, meetings: 5, aiActions: 12 },
  { day: 'Wed', tasks: 8, emails: 32, meetings: 2, aiActions: 15 },
  { day: 'Thu', tasks: 20, emails: 15, meetings: 4, aiActions: 10 },
  { day: 'Fri', tasks: 18, emails: 22, meetings: 6, aiActions: 14 },
  { day: 'Sat', tasks: 5, emails: 8, meetings: 0, aiActions: 3 },
  { day: 'Sun', tasks: 2, emails: 4, meetings: 0, aiActions: 1 },
];

const monthlyData = [
  { week: 'Week 1', productivity: 78, timeSaved: 4.2 },
  { week: 'Week 2', productivity: 82, timeSaved: 5.1 },
  { week: 'Week 3', productivity: 85, timeSaved: 6.3 },
  { week: 'Week 4', productivity: 91, timeSaved: 7.8 },
];

const aiProductivityStats = {
  totalTimeSaved: 23.5,
  tasksAutoGenerated: 47,
  emailsAnalyzed: 156,
  meetingsSummarized: 12,
  productivityIncrease: 34,
};

const getActivityIcon = (type: string) => {
  switch (type) {
    case 'task': return CheckCircle2;
    case 'email': return Mail;
    case 'meeting': return Calendar;
    case 'document': return FileText;
    case 'ai': return Sparkles;
    default: return Activity;
  }
};

const getActivityColor = (type: string) => {
  switch (type) {
    case 'task': return 'text-emerald-500 bg-emerald-500/10';
    case 'email': return 'text-blue-500 bg-blue-500/10';
    case 'meeting': return 'text-purple-500 bg-purple-500/10';
    case 'document': return 'text-amber-500 bg-amber-500/10';
    case 'ai': return 'text-primary bg-primary/10';
    default: return 'text-muted-foreground bg-muted';
  }
};

const StatCard = ({ stat, period }: { stat: ProductivityStat; period: string }) => {
  const Icon = stat.icon;
  const isPositive = stat.change >= 0;

  return (
    <Card>
      <CardContent className="p-4">
        <div className="flex items-start justify-between">
          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
            <Icon className="h-5 w-5 text-primary" />
          </div>
          <Badge variant={isPositive ? 'default' : 'destructive'} className="gap-1">
            {isPositive ? <ArrowUp className="h-3 w-3" /> : <ArrowDown className="h-3 w-3" />}
            {Math.abs(stat.change)}%
          </Badge>
        </div>
        <div className="mt-3">
          <p className="text-2xl font-bold text-foreground">
            {stat.value}{stat.unit}
          </p>
          <p className="text-sm text-muted-foreground">{stat.label}</p>
        </div>
      </CardContent>
    </Card>
  );
};

const AIProductivityCard = () => (
  <Card className="border-primary/20 bg-gradient-to-br from-primary/5 to-transparent">
    <CardHeader className="pb-3">
      <CardTitle className="flex items-center gap-2">
        <Brain className="h-5 w-5 text-primary" />
        AI Productivity Impact
      </CardTitle>
    </CardHeader>
    <CardContent className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <Timer className="h-4 w-4 text-emerald-500" />
            <span className="text-sm text-muted-foreground">Time Saved</span>
          </div>
          <p className="text-2xl font-bold text-foreground">{aiProductivityStats.totalTimeSaved}h</p>
          <p className="text-xs text-muted-foreground">This week</p>
        </div>
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-primary" />
            <span className="text-sm text-muted-foreground">Productivity</span>
          </div>
          <p className="text-2xl font-bold text-foreground">+{aiProductivityStats.productivityIncrease}%</p>
          <p className="text-xs text-muted-foreground">Increase</p>
        </div>
      </div>

      <div className="space-y-3 pt-3 border-t border-border">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            <span className="text-sm text-foreground">Tasks Auto-Generated</span>
          </div>
          <span className="font-semibold text-foreground">{aiProductivityStats.tasksAutoGenerated}</span>
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Mail className="h-4 w-4 text-blue-500" />
            <span className="text-sm text-foreground">Emails Analyzed</span>
          </div>
          <span className="font-semibold text-foreground">{aiProductivityStats.emailsAnalyzed}</span>
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <MessageSquare className="h-4 w-4 text-purple-500" />
            <span className="text-sm text-foreground">Meetings Summarized</span>
          </div>
          <span className="font-semibold text-foreground">{aiProductivityStats.meetingsSummarized}</span>
        </div>
      </div>

      <div className="pt-3 border-t border-border">
        <p className="text-xs text-muted-foreground mb-2">Weekly AI Efficiency</p>
        <Progress value={aiProductivityStats.productivityIncrease + 50} className="h-2" />
        <p className="text-xs text-muted-foreground mt-1">
          AI has helped complete tasks {aiProductivityStats.productivityIncrease}% faster
        </p>
      </div>
    </CardContent>
  </Card>
);

const ActivityView = () => {
  const [period, setPeriod] = useState('today');
  const { activities } = useRealtimeActivity();

  const dailyStats: ProductivityStat[] = [
    { label: 'Tasks Completed', value: 12, unit: '', change: 20, icon: CheckCircle2 },
    { label: 'Emails Processed', value: 28, unit: '', change: 15, icon: Mail },
    { label: 'Time Saved by AI', value: 2.5, unit: 'h', change: 35, icon: Zap },
    { label: 'Focus Score', value: 87, unit: '%', change: 8, icon: Target },
  ];

  const weeklyStats: ProductivityStat[] = [
    { label: 'Tasks Completed', value: 78, unit: '', change: 12, icon: CheckCircle2 },
    { label: 'Emails Processed', value: 123, unit: '', change: 8, icon: Mail },
    { label: 'Time Saved by AI', value: 23.5, unit: 'h', change: 42, icon: Zap },
    { label: 'Avg Focus Score', value: 82, unit: '%', change: 5, icon: Target },
  ];

  const monthlyStats: ProductivityStat[] = [
    { label: 'Tasks Completed', value: 312, unit: '', change: 18, icon: CheckCircle2 },
    { label: 'Emails Processed', value: 489, unit: '', change: 22, icon: Mail },
    { label: 'Time Saved by AI', value: 94, unit: 'h', change: 56, icon: Zap },
    { label: 'Productivity Score', value: 91, unit: '%', change: 15, icon: Target },
  ];

  const getStats = () => {
    switch (period) {
      case 'today': return dailyStats;
      case 'week': return weeklyStats;
      case 'month': return monthlyStats;
      default: return dailyStats;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Activity</h1>
          <p className="text-muted-foreground">Track your daily productivity and AI impact</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm">Export Report</Button>
        </div>
      </div>

      {/* Period Tabs */}
      <Tabs value={period} onValueChange={setPeriod}>
        <TabsList>
          <TabsTrigger value="today">Today</TabsTrigger>
          <TabsTrigger value="week">This Week</TabsTrigger>
          <TabsTrigger value="month">This Month</TabsTrigger>
        </TabsList>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 mt-6">
          {getStats().map((stat) => (
            <StatCard key={stat.label} stat={stat} period={period} />
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mt-6">
          {/* Activity Timeline - Takes 2 columns */}
          <div className="lg:col-span-2 space-y-6">
            <TabsContent value="today" className="mt-0">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Activity className="h-5 w-5" />
                    Today's Activity
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {todayActivities.map((activity) => {
                      const Icon = getActivityIcon(activity.type);
                      const colorClass = getActivityColor(activity.type);

                      return (
                        <div key={activity.id} className="flex items-start gap-4">
                          <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${colorClass}`}>
                            <Icon className="h-5 w-5" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <span className="font-medium text-foreground">{activity.action}</span>
                              {activity.aiAssisted && (
                                <Badge variant="secondary" className="gap-1 text-xs">
                                  <Sparkles className="h-3 w-3" />
                                  AI
                                </Badge>
                              )}
                            </div>
                            <p className="text-sm text-muted-foreground truncate">{activity.description}</p>
                            <div className="flex items-center gap-3 mt-1">
                              <span className="text-xs text-muted-foreground">{activity.time}</span>
                              {activity.timeSaved && (
                                <span className="text-xs text-emerald-500 flex items-center gap-1">
                                  <Clock className="h-3 w-3" />
                                  {activity.timeSaved} min saved
                                </span>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="week" className="mt-0">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Activity className="h-5 w-5" />
                    Weekly Activity Overview
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="h-[300px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={weeklyData}>
                        <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                        <XAxis dataKey="day" className="text-muted-foreground" />
                        <YAxis className="text-muted-foreground" />
                        <Tooltip
                          contentStyle={{
                            backgroundColor: 'hsl(var(--card))',
                            border: '1px solid hsl(var(--border))',
                            borderRadius: '8px',
                          }}
                        />
                        <Bar dataKey="tasks" name="Tasks" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
                        <Bar dataKey="emails" name="Emails" fill="hsl(220 90% 60%)" radius={[4, 4, 0, 0]} />
                        <Bar dataKey="aiActions" name="AI Actions" fill="hsl(280 80% 60%)" radius={[4, 4, 0, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="month" className="mt-0">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <TrendingUp className="h-5 w-5" />
                    Monthly Productivity Trend
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="h-[300px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={monthlyData}>
                        <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                        <XAxis dataKey="week" className="text-muted-foreground" />
                        <YAxis className="text-muted-foreground" />
                        <Tooltip
                          contentStyle={{
                            backgroundColor: 'hsl(var(--card))',
                            border: '1px solid hsl(var(--border))',
                            borderRadius: '8px',
                          }}
                        />
                        <Area
                          type="monotone"
                          dataKey="productivity"
                          name="Productivity %"
                          stroke="hsl(var(--primary))"
                          fill="hsl(var(--primary) / 0.2)"
                        />
                        <Area
                          type="monotone"
                          dataKey="timeSaved"
                          name="Hours Saved"
                          stroke="hsl(142 70% 45%)"
                          fill="hsl(142 70% 45% / 0.2)"
                        />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </div>

          {/* AI Productivity Card - Right sidebar */}
          <div className="space-y-6">
            {/* Live Team Activity */}
            <Card>
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-base">
                  <Radio className="h-4 w-4 text-success animate-pulse" />
                  Live Team Activity
                </CardTitle>
              </CardHeader>
              <CardContent>
                <LiveActivityFeed activities={activities} />
              </CardContent>
            </Card>

            <AIProductivityCard />

            {/* AI Insights */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base">
                  <Sparkles className="h-5 w-5 text-primary" />
                  AI Insights
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
                  <p className="text-sm text-foreground font-medium">Peak Productivity</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    Your most productive hours are 9 AM - 12 PM. AI suggests scheduling complex tasks during this window.
                  </p>
                </div>
                <div className="p-3 rounded-lg bg-primary/10 border border-primary/20">
                  <p className="text-sm text-foreground font-medium">Time Saved This Week</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    AI automation saved you 23.5 hours this week, equivalent to 3 full working days.
                  </p>
                </div>
                <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/20">
                  <p className="text-sm text-foreground font-medium">Recommendation</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    Enable AI auto-replies for routine emails to save an additional 5+ hours weekly.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </Tabs>
    </div>
  );
};

export default ActivityView;
