import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import {
  FileText,
  Calendar,
  TrendingUp,
  Users,
  AlertTriangle,
  Download,
  Copy,
  Sparkles,
  Clock,
  CheckCircle2,
  Loader2,
  History,
} from 'lucide-react';

interface ReportType {
  id: string;
  name: string;
  description: string;
  icon: React.ElementType;
  frequency: string;
  color: string;
}

interface GeneratedReport {
  id: string;
  type: string;
  name: string;
  content: string;
  generatedAt: string;
}

const reportTypes: ReportType[] = [
  {
    id: 'weekly-status',
    name: 'Weekly Status Report',
    description: 'Comprehensive overview of weekly progress, accomplishments, and upcoming tasks',
    icon: Calendar,
    frequency: 'Weekly',
    color: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
  },
  {
    id: 'monthly-summary',
    name: 'Monthly Summary',
    description: 'Detailed monthly analysis with KPIs, budget status, and strategic insights',
    icon: TrendingUp,
    frequency: 'Monthly',
    color: 'bg-primary/10 text-primary border-primary/20',
  },
  {
    id: 'stakeholder-update',
    name: 'Stakeholder Update',
    description: 'Executive-level summary for stakeholders with key decisions and project health',
    icon: Users,
    frequency: 'Bi-weekly',
    color: 'bg-purple-500/10 text-purple-500 border-purple-500/20',
  },
  {
    id: 'risk-assessment',
    name: 'Risk Assessment',
    description: 'Comprehensive risk analysis with mitigation strategies and trend analysis',
    icon: AlertTriangle,
    frequency: 'Weekly',
    color: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
  },
  {
    id: 'team-performance',
    name: 'Team Performance',
    description: 'Team productivity metrics, AI efficiency gains, and collaboration insights',
    icon: Users,
    frequency: 'Weekly',
    color: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
  },
];

// Mock project data to send to AI
const mockProjectData = {
  projectName: "Digital Transformation Initiative",
  period: "December 9-15, 2024",
  team: {
    size: 12,
    members: ["Sarah Mitchell (PM)", "James Wilson (Tech Lead)", "Emily Chen (Designer)", "David Park (Developer)"]
  },
  tasks: {
    completed: 28,
    inProgress: 15,
    blocked: 2,
    total: 45
  },
  milestones: {
    achieved: ["Phase 1 API Integration Complete", "User Testing Round 1"],
    upcoming: ["Beta Launch - Dec 20", "Stakeholder Demo - Dec 22"]
  },
  budget: {
    allocated: 150000,
    spent: 87500,
    remaining: 62500,
    percentUsed: 58.3
  },
  risks: [
    { name: "API vendor delays", severity: "high", status: "mitigating" },
    { name: "Resource availability", severity: "medium", status: "monitoring" }
  ],
  aiMetrics: {
    timeSavedHours: 23.5,
    tasksAutoGenerated: 47,
    emailsAnalyzed: 156,
    meetingsSummarized: 12,
    productivityIncrease: 34
  },
  meetings: {
    held: 8,
    actionItemsGenerated: 24,
    avgDuration: "45 mins"
  },
  communications: {
    emailsProcessed: 156,
    stakeholderUpdates: 3,
    teamMessages: 89
  }
};

const ReportsView = () => {
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState('generate');
  const [isGenerating, setIsGenerating] = useState<string | null>(null);
  const [generatedReports, setGeneratedReports] = useState<GeneratedReport[]>([]);
  const [selectedReport, setSelectedReport] = useState<GeneratedReport | null>(null);

  const handleGenerateReport = async (reportType: ReportType) => {
    setIsGenerating(reportType.id);
    
    try {
      const { data, error } = await supabase.functions.invoke('generate-report', {
        body: { 
          reportType: reportType.id,
          projectData: mockProjectData 
        }
      });

      if (error) throw error;

      if (data.error) {
        throw new Error(data.error);
      }

      const newReport: GeneratedReport = {
        id: Date.now().toString(),
        type: reportType.id,
        name: reportType.name,
        content: data.report,
        generatedAt: data.generatedAt,
      };

      setGeneratedReports(prev => [newReport, ...prev]);
      setSelectedReport(newReport);
      setActiveTab('view');

      toast({
        title: "Report Generated",
        description: `${reportType.name} has been generated successfully.`,
      });
    } catch (error) {
      console.error('Error generating report:', error);
      toast({
        title: "Generation Failed",
        description: error instanceof Error ? error.message : "Failed to generate report. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(null);
    }
  };

  const handleCopyReport = async () => {
    if (!selectedReport) return;
    
    try {
      await navigator.clipboard.writeText(selectedReport.content);
      toast({
        title: "Copied",
        description: "Report content copied to clipboard.",
      });
    } catch {
      toast({
        title: "Copy Failed",
        description: "Failed to copy report content.",
        variant: "destructive",
      });
    }
  };

  const handleDownloadReport = () => {
    if (!selectedReport) return;
    
    const blob = new Blob([selectedReport.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedReport.type}-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Downloaded",
      description: "Report has been downloaded as markdown.",
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Auto-Generated Reports</h1>
          <p className="text-muted-foreground">AI-powered reports from your project data</p>
        </div>
        <Badge variant="secondary" className="gap-1">
          <Sparkles className="h-3 w-3" />
          Powered by AI
        </Badge>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="generate">Generate Report</TabsTrigger>
          <TabsTrigger value="view" disabled={!selectedReport}>
            View Report {selectedReport && <CheckCircle2 className="h-3 w-3 ml-1" />}
          </TabsTrigger>
          <TabsTrigger value="history">
            History ({generatedReports.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="generate" className="mt-6">
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
            {reportTypes.map((report) => {
              const Icon = report.icon;
              const isLoading = isGenerating === report.id;

              return (
                <Card key={report.id} className={`hover:shadow-md transition-all ${report.color} border-2`}>
                  <CardHeader className="pb-3">
                    <div className="flex items-start justify-between">
                      <div className="w-12 h-12 rounded-xl bg-background flex items-center justify-center">
                        <Icon className="h-6 w-6" />
                      </div>
                      <Badge variant="outline">{report.frequency}</Badge>
                    </div>
                    <CardTitle className="text-lg mt-3">{report.name}</CardTitle>
                    <CardDescription>{report.description}</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <Button 
                      className="w-full gap-2" 
                      onClick={() => handleGenerateReport(report)}
                      disabled={isLoading || isGenerating !== null}
                    >
                      {isLoading ? (
                        <>
                          <Loader2 className="h-4 w-4 animate-spin" />
                          Generating...
                        </>
                      ) : (
                        <>
                          <Sparkles className="h-4 w-4" />
                          Generate Report
                        </>
                      )}
                    </Button>
                  </CardContent>
                </Card>
              );
            })}
          </div>

          {/* AI Info Card */}
          <Card className="mt-6 bg-gradient-to-br from-primary/5 to-transparent border-primary/20">
            <CardContent className="p-6">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center">
                  <Sparkles className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground">How AI Reports Work</h3>
                  <p className="text-sm text-muted-foreground mt-1">
                    Reports are automatically generated by analyzing your project data including tasks, 
                    meetings, emails, and activity metrics. AI synthesizes this information into 
                    professional, actionable reports that would typically take hours to create manually.
                  </p>
                  <div className="flex flex-wrap gap-4 mt-4 text-sm">
                    <div className="flex items-center gap-2 text-emerald-500">
                      <Clock className="h-4 w-4" />
                      <span>Saves 2-4 hours per report</span>
                    </div>
                    <div className="flex items-center gap-2 text-primary">
                      <CheckCircle2 className="h-4 w-4" />
                      <span>Consistent formatting</span>
                    </div>
                    <div className="flex items-center gap-2 text-blue-500">
                      <FileText className="h-4 w-4" />
                      <span>Export to Markdown/PDF</span>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="view" className="mt-6">
          {selectedReport && (
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="flex items-center gap-2">
                      <FileText className="h-5 w-5" />
                      {selectedReport.name}
                    </CardTitle>
                    <CardDescription className="flex items-center gap-2 mt-1">
                      <Clock className="h-3 w-3" />
                      Generated {new Date(selectedReport.generatedAt).toLocaleString()}
                    </CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={handleCopyReport}>
                      <Copy className="h-4 w-4 mr-1" />
                      Copy
                    </Button>
                    <Button variant="outline" size="sm" onClick={handleDownloadReport}>
                      <Download className="h-4 w-4 mr-1" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <ScrollArea className="h-[500px] pr-4">
                  <div className="prose prose-sm dark:prose-invert max-w-none">
                    <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed bg-muted/50 p-4 rounded-lg">
                      {selectedReport.content}
                    </pre>
                  </div>
                </ScrollArea>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="history" className="mt-6">
          {generatedReports.length === 0 ? (
            <Card>
              <CardContent className="p-12 text-center">
                <History className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                <h3 className="font-semibold text-foreground mb-2">No Reports Yet</h3>
                <p className="text-muted-foreground mb-4">
                  Generate your first report to see it here
                </p>
                <Button onClick={() => setActiveTab('generate')}>
                  Generate Report
                </Button>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {generatedReports.map((report) => (
                <Card 
                  key={report.id} 
                  className="hover:shadow-md transition-shadow cursor-pointer"
                  onClick={() => {
                    setSelectedReport(report);
                    setActiveTab('view');
                  }}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                          <FileText className="h-5 w-5 text-primary" />
                        </div>
                        <div>
                          <p className="font-medium text-foreground">{report.name}</p>
                          <p className="text-sm text-muted-foreground">
                            {new Date(report.generatedAt).toLocaleString()}
                          </p>
                        </div>
                      </div>
                      <Button variant="ghost" size="sm">
                        View
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default ReportsView;
