-- ============================================================================
-- Nexus OS - Azure PostgreSQL Data Import Script
-- Description: Import data from CSV files exported from Supabase
-- Usage: Run this script against your Azure PostgreSQL database
-- ============================================================================

-- ============================================================================
-- INSTRUCTIONS:
-- 1. Ensure all migrations have been run first (./migrate.sh)
-- 2. Upload CSV files to Azure Blob Storage or accessible location
-- 3. Update the file paths below to match your environment
-- 4. Run this script to import the data
-- ============================================================================

-- Disable triggers temporarily for faster import
SET session_replication_role = replica;

-- ============================================================================
-- Clear existing data (optional - comment out if appending)
-- ============================================================================

-- TRUNCATE TABLE ai_output_audit_logs CASCADE;
-- TRUNCATE TABLE user_activities CASCADE;
-- TRUNCATE TABLE company_branding CASCADE;
-- TRUNCATE TABLE email_templates CASCADE;
-- TRUNCATE TABLE document_templates CASCADE;
-- TRUNCATE TABLE documents CASCADE;
-- TRUNCATE TABLE decision_audit_logs CASCADE;
-- TRUNCATE TABLE decisions CASCADE;
-- TRUNCATE TABLE tenant_settings CASCADE;
-- TRUNCATE TABLE role_requests CASCADE;
-- TRUNCATE TABLE role_definitions CASCADE;
-- TRUNCATE TABLE user_roles CASCADE;
-- TRUNCATE TABLE profiles CASCADE;

-- ============================================================================
-- Import Tables (update paths as needed)
-- ============================================================================

-- Import profiles
\COPY profiles (id, user_id, display_name, avatar_url, created_at, updated_at) FROM '/data/import/profiles.csv' WITH CSV HEADER;

-- Import user_roles
\COPY user_roles (id, user_id, role, created_at) FROM '/data/import/user_roles.csv' WITH CSV HEADER;

-- Import role_definitions
\COPY role_definitions (id, role, display_name, description, permissions, hierarchy_level, created_at, updated_at) FROM '/data/import/role_definitions.csv' WITH CSV HEADER;

-- Import role_requests
\COPY role_requests (id, user_id, requested_role, status, admin_notes, reviewed_by, reviewed_at, created_at, updated_at) FROM '/data/import/role_requests.csv' WITH CSV HEADER;

-- Import tenant_settings
\COPY tenant_settings (id, setting_key, setting_value, category, description, updated_by, created_at, updated_at) FROM '/data/import/tenant_settings.csv' WITH CSV HEADER;

-- Import decisions
\COPY decisions (id, user_id, title, description, decision_type, status, priority, project_name, amount, impact, rationale, stakeholders, due_date, decided_at, decided_by, created_at, updated_at) FROM '/data/import/decisions.csv' WITH CSV HEADER;

-- Import decision_audit_logs
\COPY decision_audit_logs (id, decision_id, user_id, action, previous_status, new_status, notes, created_at) FROM '/data/import/decision_audit_logs.csv' WITH CSV HEADER;

-- Import documents (search_vector will be auto-generated by trigger)
\COPY documents (id, user_id, title, content, file_name, file_type, created_at, updated_at) FROM '/data/import/documents.csv' WITH CSV HEADER;

-- Import document_templates
\COPY document_templates (id, user_id, name, type, content, is_default, created_at, updated_at) FROM '/data/import/document_templates.csv' WITH CSV HEADER;

-- Import email_templates
\COPY email_templates (id, user_id, name, type, subject, body, is_default, created_at, updated_at) FROM '/data/import/email_templates.csv' WITH CSV HEADER;

-- Import company_branding
\COPY company_branding (id, user_id, company_name, tagline, logo_url, primary_color, secondary_color, accent_color, font_heading, font_body, created_at, updated_at) FROM '/data/import/company_branding.csv' WITH CSV HEADER;

-- Import user_activities
\COPY user_activities (id, user_id, action_type, page_path, action_details, created_at) FROM '/data/import/user_activities.csv' WITH CSV HEADER;

-- Import ai_output_audit_logs
\COPY ai_output_audit_logs (id, user_id, report_type, report_name, previous_status, new_status, notes, created_at) FROM '/data/import/ai_output_audit_logs.csv' WITH CSV HEADER;

-- ============================================================================
-- Re-enable triggers
-- ============================================================================

SET session_replication_role = DEFAULT;

-- ============================================================================
-- Update search vectors for documents
-- ============================================================================

UPDATE documents SET search_vector = to_tsvector('english', COALESCE(title, '') || ' ' || COALESCE(content, ''));

-- ============================================================================
-- Verify Import
-- ============================================================================

SELECT 'profiles' as table_name, COUNT(*) as row_count FROM profiles
UNION ALL SELECT 'user_roles', COUNT(*) FROM user_roles
UNION ALL SELECT 'role_definitions', COUNT(*) FROM role_definitions
UNION ALL SELECT 'role_requests', COUNT(*) FROM role_requests
UNION ALL SELECT 'tenant_settings', COUNT(*) FROM tenant_settings
UNION ALL SELECT 'decisions', COUNT(*) FROM decisions
UNION ALL SELECT 'decision_audit_logs', COUNT(*) FROM decision_audit_logs
UNION ALL SELECT 'documents', COUNT(*) FROM documents
UNION ALL SELECT 'document_templates', COUNT(*) FROM document_templates
UNION ALL SELECT 'email_templates', COUNT(*) FROM email_templates
UNION ALL SELECT 'company_branding', COUNT(*) FROM company_branding
UNION ALL SELECT 'user_activities', COUNT(*) FROM user_activities
UNION ALL SELECT 'ai_output_audit_logs', COUNT(*) FROM ai_output_audit_logs
ORDER BY table_name;
