#!/bin/bash
# ============================================================================
# AWS Infrastructure Deployment Script
# Usage: ./deploy.sh <environment>
# Example: ./deploy.sh dev
# ============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
PROJECT_NAME="masira"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CLOUDFORMATION_DIR="$ROOT_DIR/cloudformation"
PARAMETERS_DIR="$ROOT_DIR/parameters"

# Validate arguments
if [ $# -lt 1 ]; then
    echo -e "${RED}Error: Environment argument required${NC}"
    echo "Usage: $0 <environment>"
    echo "Environments: dev, staging, prod"
    exit 1
fi

ENVIRONMENT=$1
STACK_NAME="${PROJECT_NAME}-${ENVIRONMENT}"

# Validate environment
if [[ ! "$ENVIRONMENT" =~ ^(dev|staging|prod)$ ]]; then
    echo -e "${RED}Error: Invalid environment '$ENVIRONMENT'${NC}"
    echo "Valid environments: dev, staging, prod"
    exit 1
fi

# Load environment parameters
PARAMS_FILE="$PARAMETERS_DIR/${ENVIRONMENT}.json"
if [ ! -f "$PARAMS_FILE" ]; then
    echo -e "${YELLOW}Warning: Parameters file not found at $PARAMS_FILE${NC}"
    echo "Using default parameters..."
    PARAMS_FILE=""
fi

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Deploying Masira to AWS${NC}"
echo -e "${GREEN}Environment: $ENVIRONMENT${NC}"
echo -e "${GREEN}Stack Name: $STACK_NAME${NC}"
echo -e "${GREEN}========================================${NC}"

# Check AWS CLI configuration
echo -e "\n${YELLOW}Checking AWS CLI configuration...${NC}"
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}Error: AWS CLI not configured. Run 'aws configure' first.${NC}"
    exit 1
fi

AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=$(aws configure get region)
echo -e "${GREEN}AWS Account: $AWS_ACCOUNT${NC}"
echo -e "${GREEN}AWS Region: $AWS_REGION${NC}"

# Validate CloudFormation template
echo -e "\n${YELLOW}Validating CloudFormation template...${NC}"
aws cloudformation validate-template \
    --template-body "file://$CLOUDFORMATION_DIR/main.yaml" \
    > /dev/null

echo -e "${GREEN}Template validation successful${NC}"

# Build parameter overrides
PARAM_OVERRIDES="Environment=$ENVIRONMENT ProjectName=$PROJECT_NAME"

# Add parameters from file if exists
if [ -n "$PARAMS_FILE" ] && [ -f "$PARAMS_FILE" ]; then
    while IFS= read -r line; do
        key=$(echo "$line" | jq -r '.ParameterKey')
        value=$(echo "$line" | jq -r '.ParameterValue')
        if [ "$key" != "null" ] && [ "$value" != "null" ]; then
            PARAM_OVERRIDES="$PARAM_OVERRIDES $key=$value"
        fi
    done < <(jq -c '.[]' "$PARAMS_FILE")
fi

# Deploy CloudFormation stack
echo -e "\n${YELLOW}Deploying CloudFormation stack...${NC}"
echo "This may take 15-20 minutes for initial deployment..."

aws cloudformation deploy \
    --template-file "$CLOUDFORMATION_DIR/main.yaml" \
    --stack-name "$STACK_NAME" \
    --parameter-overrides $PARAM_OVERRIDES \
    --capabilities CAPABILITY_NAMED_IAM \
    --tags Environment="$ENVIRONMENT" Project="$PROJECT_NAME"

echo -e "${GREEN}Stack deployment completed${NC}"

# Get stack outputs
echo -e "\n${YELLOW}Retrieving stack outputs...${NC}"

get_output() {
    aws cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
        --output text
}

DB_ENDPOINT=$(get_output "DatabaseEndpoint")
USER_POOL_ID=$(get_output "UserPoolId")
USER_POOL_CLIENT_ID=$(get_output "UserPoolClientId")
IDENTITY_POOL_ID=$(get_output "IdentityPoolId")
API_URL=$(get_output "ApiGatewayUrl")
AMPLIFY_DOMAIN=$(get_output "AmplifyDefaultDomain")
S3_BUCKET=$(get_output "FileStorageBucketName")

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "Database Endpoint:    ${DB_ENDPOINT}"
echo -e "User Pool ID:         ${USER_POOL_ID}"
echo -e "User Pool Client ID:  ${USER_POOL_CLIENT_ID}"
echo -e "Identity Pool ID:     ${IDENTITY_POOL_ID}"
echo -e "API Gateway URL:      ${API_URL}"
echo -e "Amplify Domain:       https://${AMPLIFY_DOMAIN}"
echo -e "S3 Bucket:            ${S3_BUCKET}"
echo ""

# Create .env file for local development
ENV_FILE="$ROOT_DIR/../../.env.aws.$ENVIRONMENT"
cat > "$ENV_FILE" << EOF
# AWS Configuration for $ENVIRONMENT
# Generated by deploy.sh on $(date)

VITE_AWS_REGION=$AWS_REGION
VITE_USER_POOL_ID=$USER_POOL_ID
VITE_USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID
VITE_IDENTITY_POOL_ID=$IDENTITY_POOL_ID
VITE_API_URL=$API_URL
VITE_S3_BUCKET=$S3_BUCKET
VITE_ENVIRONMENT=$ENVIRONMENT
EOF

echo -e "${GREEN}Environment file created: $ENV_FILE${NC}"
echo ""

# Next steps
echo -e "${YELLOW}Next Steps:${NC}"
echo "1. Run database migrations: ./migrate-db.sh $ENVIRONMENT"
echo "2. Connect Amplify to GitHub repository in AWS Console"
echo "3. Trigger initial build in Amplify Console"
echo "4. (Optional) Configure custom domain in Amplify"
echo ""
echo -e "${GREEN}Deployment successful!${NC}"
